### PR TITLE
Parse files included in messages.

### PR DESCRIPTION
**Pull request by leameow**
@aviau for review

### CODE REVIEW

**Comment by leameow** [comment]
Ping!

**Comment by aviau** [comment]
Nice! LGTM!

Sorry for the delay I don't have GH emails

**Comment by aviau** [comment]
Should we put an id/class on the ``<a>`` or something so that we can distinguish them easily?

I can see us adding similar links for shared contacts.

So we can do ```for each file in msg.findall("<a>", id="shared_file")```

We can also put the mimetype and filesize in html attributes too so that we can parse them better. data attributes exist exactly for this

Also might as well add the md5. Can be useful in dedup / analysis / whatever

```
<a
    href="https://sdfsdf.jpg"
    id="shared_file"
    data-mime="content/jpeg/blbla"
    data-md5="3h45j3453452"
    data-filesize="30mb">
        cat.jpg [jpeg 3mb]
</a>
```

**Comment by leameow** [comment]
Good idea, will do!

**Pull request merged**
